Repository totvslabs/pyCarol, pull requests merged in 2020-07, with the labels that each got.

#482 docs: documentation for PwdKeyAuth
  README.rst
  doc/source/conf.py
  doc/source/pycarol/auth.rst
  doc/source/pycarol/pipeline.rst
  doc/source/pycarol/pyCarol.rst
  pycarol/auth/ApiKeyAuth.py
  pycarol/auth/PwdAuth.py
  pycarol/auth/PwdKeyAuth.py
  setup.py
Labels: component/docs, difficulty/easy, priority/normal

#483 bug:validate-org-info
  pycarol/carol.py
Labels: difficulty/easy, kind/bug, priority/normal

#484 Fix datamodel validation
  pycarol/__init__.py
  pycarol/carol.py
  pycarol/data_models/data_models.py
  pycarol/exceptions.py
Labels: difficulty/easy, kind/bug, priority/normal

#485 fix: pandas not required
  pycarol/data_models/data_models.py
  pycarol/staging.py
  pycarol/utils/miscellaneous.py
Labels: difficulty/easy, kind/enhancement, priority/normal

#486 feat: retry fetching files from CDS
  pycarol/utils/_cds_utils.py
  pycarol/utils/storage_gcpcs.py
  setup.py
Labels: difficulty/easy, priority/low
