Repository totvslabs/pyCarol, pull requests merged in 2020-04, with the labels that each got.

#454 new PwdKeyAuth method
  pycarol/__init__.py
  pycarol/auth/PwdKeyAuth.py
Labels: difficulty/easy, kind/enhancement, priority/normal

#455 Metadata fetch parquet
  pycarol/__init__.py
  pycarol/data_models/data_models.py
  pycarol/staging.py
Labels: difficulty/easy, kind/enhancement, priority/low

#458 remove machines not supported.
  pycarol/cds.py
Labels: difficulty/easy, kind/bug, priority/normal

#457 send data to the sync API
  pycarol/staging.py
Labels: difficulty/easy, kind/enhancement, priority/normal

#459 fix: reviewing Tasks' methods
  pycarol/tasks.py
Labels: difficulty/easy, kind/enhancement, priority/normal

#460 add support to lazy execute when using the PwdKeyAuth
  pycarol/auth/PwdKeyAuth.py
  pycarol/carol.py
Labels: difficulty/easy, kind/enhancement, priority/low
