Repository totvslabs/pyCarol, pull requests merged in 2020-02, with the labels that each got.

#436 feat: added mergeable bot
  .github/mergeable.yml
Labels: difficulty/easy, kind/enhancement, priority/low

#438 Drop Staging tables endpoints.
  pycarol/staging.py
Labels: difficulty/easy, kind/enhancement

#437 More documentation
  README.rst
  pycarol/carol.py
  pycarol/cds.py
  pycarol/query.py
  pycarol/staging.py
  pycarol/storage.py
  setup.cfg
  setup.py
Labels: difficulty/easy, kind/enhancement

#439 fix: added dependabot config
  .dependabot/config.yml
Labels: difficulty/easy, kind/enhancement, priority/low

#440 More documentation
  pycarol/carol.py
  pycarol/carolina.py
  pycarol/cds.py
  pycarol/filter.py
  pycarol/query.py
  pycarol/staging.py
  pycarol/storage.py
  setup.py
Labels: component/docs, difficulty/easy, kind/enhancement

#441 Docs
  pycarol/apps.py
  pycarol/cds.py
  pycarol/connectors.py
  pycarol/filter.py
  pycarol/logger.py
  pycarol/query.py
  pycarol/staging.py
  pycarol/tools/__init__.py
  pycarol/tools/clone_tenant.py
  pycarol/tools/data_model_generator.py
Labels: component/docs, difficulty/easy, kind/enhancement

#442 added chunk_size param to Storage.save and Storage.load
  pycarol/storage.py
  pycarol/utils/storage_gcpcs.py
Labels: difficulty/easy, kind/enhancement
