Repository totvslabs/pyCarol, pull requests merged in 2020-08, with the labels that each got.

#487 feat: retry when logs data to carol.
  pycarol/logger.py
  pycarol/pipeline/tools/_tools.py
  pycarol/tasks.py
Labels: difficulty/easy, kind/bug, priority/normal

#488 bug: fix dag creation
  pycarol/pipeline/tools/_tools.py
Labels: difficulty/medium, kind/bug, priority/normal

#489 fix: buildkite queue name
  .buildkite/pipeline.sh
Labels: difficulty/easy, kind/bug, priority/normal

#491 pyarrow<1
  setup.py
Labels: difficulty/easy, kind/bug, priority/normal

#490 feat: fetch rejected records from cds
  pycarol/__init__.py
  pycarol/carolina.py
  pycarol/data_models/data_models.py
  pycarol/storage.py
  pycarol/utils/importers.py
  pycarol/utils/storage_gcpcs.py
Labels: difficulty/medium, kind/enhancement, priority/normal

#492 feat: allow to creat Carol with env variables only.
  pycarol/carol.py
Labels: difficulty/easy, kind/bug, priority/low
