Repository totvslabs/pyCarol, pull requests merged in 2020-05, with the labels that each got.

#461 build docker
  pycarol/apps.py
  pycarol/compute.py
  pycarol/query.py
Labels: difficulty/easy, kind/enhancement, priority/low

#462 fix: return tasks when building docker images from git
  pycarol/apps.py
Labels: difficulty/easy

#463 Cds update apis
  pycarol/cds.py
Labels: difficulty/easy, kind/enhancement, priority/low

#464 Stack Drive logs
  pycarol/compute.py
Labels: difficulty/easy, kind/enhancement, priority/normal

#465 Remove exporter
  pycarol/data_models/data_model_view.py
  pycarol/data_models/data_models.py
  pycarol/staging.py
  pycarol/tenant.py
Labels: difficulty/easy, priority/low

#466 feat: More install options.
  README.rst
  pycarol/app/health_check_online.py
  pycarol/apps.py
  pycarol/cds.py
  pycarol/data_models/data_model_view.py
  pycarol/data_models/data_models.py
  pycarol/logger.py
  pycarol/organization.py
  pycarol/query.py
  pycarol/schema_generator.py
  pycarol/staging.py
  pycarol/tenant.py
  pycarol/utils/deprecation_msgs.py
  pycarol/utils/importers.py
  pycarol/utils/miscellaneous.py
  pycarol/utils/storage_gcpcs.py
  setup.py
Labels: difficulty/medium, priority/low, priority/normal
