Repository totvslabs/pyCarol, pull requests merged in 2021-09, with the labels that each got.

#545 feature- add handy functions
  README.rst
  doc/source/pycarol/generated/pycarol.functions.misc.rst
  doc/source/pycarol/generated/pycarol.functions.rst
  doc/source/pycarol/pyCarol.rst
  pycarol/connectors.py
  pycarol/functions/__init__.py
  pycarol/functions/misc.py
  pycarol/logger.py
  pycarol/tasks.py
  pycarol/utils/miscellaneous.py
Labels: kind/enhancement, component/docs, priority/normal

#546 feat: Reuse sessino
  pycarol/carol.py
Labels: kind/enhancement, difficulty/easy, priority/normal

#548 Issue 547
  pycarol/utils/storage_gcpcs.py
  test/artifacts/test.txt
  test/test_storage.py
Labels: kind/enhancement, difficulty/easy, priority/normal

#549 Bigquery
  .bumpversion.cfg
  pycarol/__init__.py
  pycarol/bigquery.py
  pycarol/sql.py
  setup.py
  test/test_sql_bigquery.py
Labels: kind/enhancement, difficulty/medium, priority/normal

#550 bug: remove type annotation
  pycarol/bigquery.py
Labels: kind/bug, difficulty/easy, priority/high

#552 fixes #551
  pycarol/bigquery.py
  setup.py
  test/test_sql_bigquery.py
Labels: kind/bug, kind/enhancement, priority/normal

#554 Issue 553
  pycarol/bigquery.py
  pycarol/sql.py
Labels: kind/enhancement, difficulty/easy, component/batch, priority/low

#556 fixes #555
  setup.py
Labels: kind/bug, difficulty/easy, component/batch, priority/high

#557 get current user
  pycarol/carol.py
Labels: kind/enhancement, difficulty/easy, priority/low
