Repository totvslabs/pyCarol, pull requests merged in 2021-06, with the labels that each got.

#539 fix release docker hub
  hack/release.sh
Labels: difficulty/easy, kind/bug, priority/normal

#540 fix: make relase
  hack/release.sh
Labels: difficulty/medium, kind/bug, priority/normal

#541 remove docker hub
  Dockerfile
  Makefile
  hack/release.sh
Labels: kind/bug, kind/enhancement, priority/low, priority/normal
