Repository totvslabs/pyCarol, pull requests merged in 2021-03, with the labels that each got.

#521 feat Issue an APIkey to a connector
  pycarol/carol.py
Labels: difficulty/easy, kind/enhancement, priority/low

#522 feat: Data Model new parameter.
  pycarol/data_models/data_models.py
Labels: difficulty/easy, kind/enhancement, priority/low

#525 fix: build
  hack/setup.sh
Labels: difficulty/medium, kind/bug, priority/normal

#524 feat: Add max file size to consolidate API
  pycarol/cds.py
Labels: difficulty/easy, kind/enhancement, priority/low

#523 fix: wrong field user when untie record in CDS golden.
  pycarol/__init__.py
  pycarol/data_models/data_models.py
  pycarol/staging.py
  pycarol/utils/miscellaneous.py
Labels: difficulty/medium, kind/bug, priority/normal

#526 bug: fix empty settings
  pycarol/apps.py
Labels: difficulty/easy, kind/bug, priority/normal

#527 remove machine type verification
  pycarol/cds.py
Labels: difficulty/easy, kind/enhancement, priority/low

#528 Logo
  doc/source/conf.py
  doc/source/imgs/pycarol.svg
Labels: difficulty/easy, kind/enhancement, priority/low

#529 add user/password ans api_key to Carol
  pycarol/carol.py
Labels: difficulty/easy, kind/enhancement, priority/low

#530 feat: encapsulate some modules in a single class
  pycarol/__init__.py
  pycarol/carol.py
  pycarol/carol_api.py
  pycarol/query.py
Labels: difficulty/medium, kind/enhancement, priority/low

#531 fix
  pycarol/carol_api.py
Labels: difficulty/easy, kind/bug, priority/high

#532 feat: improve CarolAPI
  pycarol/carol_api.py
Labels: difficulty/medium, kind/enhancement, priority/normal
