Repository totvslabs/pyCarol, pull requests merged in 2023-09, with the labels that each got.

#621 Dasc 1208/add labels to bq job config
  pycarol/bigquery.py
  test/test_bigquery.py
Labels: difficulty/easy, component/online

#622 Release/2.55.0
  README.rst
  pycarol/bigquery.py
  pycarol/carol.py
  pycarol/schema_generator.py
  test/test_bigquery.py
Labels: kind/bug, kind/enhancement, difficulty/easy

#606 build: set release-drafter workflow labels
  .github/release-drafter.yml
Labels: kind/bug, difficulty/easy, priority/low
